test:
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox EncodingTest.php
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox OutputTest.php
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox ParamsTest.php
